# Path to your oh-my-zsh installation.
export ZSH="/home/alex/.oh-my-zsh"

# theme
ZSH_THEME="schminitz"

# Which plugins would you like to load?
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)
# https://github.com/zsh-users/zsh-autosuggestions
plugins=(zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# aliases
alias b="cd .."
alias bb="cd ../.."
alias bbb="cd ../../.."
alias bbbb="cd ../../../.."

alias gti="git"
alias igt="git"
alias gt="git"
alias got="git"
alias giut="git"
alias gitu="git"
alias giit="git"
alias it="git"

alias q="exit"
alias qq="exit"

alias ls="ls --color=auto --group-directories-first"
alias ll="ls -all"
alias tree="tree --dirsfirst"

alias mkdir="mkdir -p" # Automatically create intermediate non-existing directories when needed

alias dev="cd ~/Dev/"
alias down="cd ~/Downloads/"

alias vundle="vim +PluginInstall +qall" # Install all vim plugins
alias open="xdg-open"

alias ecelinux="ssh zcwen@ecelinux4.uwaterloo.ca"
alias ecetesla="ssh zcwen@ecetesla0.uwaterloo.ca"

chpwd() {
  ls
}

# unset <C-s> to pause terminal
stty -ixon

# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/alex/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/alex/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/alex/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/alex/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<


